// Code generated by goctl. DO NOT EDIT.
package types

type ApiResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message" default:"success"`
	Data    interface{} `json:"data"`
}

type ListCourseReq struct {
	Name   string `form:"name,optional"`
	Author string `form:"author,optional"`
}

type CreateCourseReq struct {
	Title  string `json:"title"`
	Author string `json:"author"`
	Source string `json:"source,optional"`
}
